name:                cardano-sl-faucet
version:             0.1.0.0
github:              "boothead/cardano-sl-faucet"
license:             BSD3
author:              "Ben Ford"
maintainer:          "ben@perurbis.com"
copyright:           "Ben Ford 2016"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/boothead/cardano-sl-faucet#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cardano-sl-faucet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cardano-sl-faucet

tests:
  cardano-sl-faucet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cardano-sl-faucet
